// ============================================================
// Day Master archetypes — keyed by Heavenly Stem character
// ============================================================
// 10 entries, one per Heavenly Stem. The Day Master is the
// backbone of the BaZi reading.
//
// FIELD SCHEMA per entry:
//
//   Reading-page fields (existing — drive the longer prose surfaces):
//     name           Indonesian archetype name (canonical).
//     chinese        Stem + element character (e.g. '丙火').
//     tagline        Canonical first-person sharable line ("Aku ...").
//     hero           2–3 sentence Indonesian prose. Who you ARE.
//     identityPills  12 short phrases; composer picks 5 per chart.
//     traits         8 phrases; composer picks 6 per chart.
//
//   Card-surface fields (TCG-style BaziCard, watercolor canvas):
//     taglineCard          Pronoun-stripped variant ("Hadir untuk ...").
//                          NO subject (no aku/kamu/dia).
//     kekuatanDescriptors  3 noun phrases. Strengths. Per bazi-card skill.
//     bayanganDescriptors  3 noun phrases. Shadows, not softened.
//     dampakDescriptors    2–3 noun phrases. What OTHERS feel around them,
//                          NOT self-descriptors.
//     sifatPills           4–6 Gen-Z behavioral phrases for the card's
//                          SIFAT zone ("drama sebentar, move on cepet"
//                          register). Composer picks 4 per chart.
//
// Card fields ship empty for 9 archetypes; 丙 prefilled from the
// reference screenshot. Card component hides empty rows gracefully.
// ============================================================

export const DAY_MASTERS = {
  '甲': {
    name: 'Pohon Oak',
    chinese: '甲木',
    subtitle: 'Pribadi yang jadi tumpuan, meski tak pernah meminta peran itu.',
    tagline: 'Aku bukan yang paling keras, tapi aku yang paling teguh.',
    hero: 'Kamu tidak pernah berteriak, tapi seluruh ruangan berubah begitu kamu melangkah masuk. Bukan karena kamu mencari perhatian, kamu hanya ada, dan kehadiranmu menenangkan seperti pohon tertua di hutan. Kamu adalah tempat berteduh bagi banyak orang, meski akarmu sendiri sudah menembus bebatuan yang tidak dilihat siapa pun.',
    identityPills: [
      'Bertahan di musim kering',
      'Akar yang tidak terlihat',
      'Punggung yang tidak pernah membungkuk',
      'Kekuatan yang diam',
      'Teguh seperti sumbu bumi',
      'Tidak bergerak karena badai',
      'Penjaga yang tidak butuh sorotan',
      'Pelindung dalam sunyi',
      'Berpijak pada prinsip sendiri',
      'Tumbuh ke atas, bukan sekadar tinggi',
      'Tidak kenal kompromi pada nilai',
      'Bersandar tanpa menjatuhkan',
    ],
    traits: [
      'Memilih diam saat kata-kata tak berarti',
      'Mengakar dalam-dalam sebelum tumbuh',
      'Pendengar yang menyimpan seluruh cerita',
      'Tidak tergesa, tapi tidak pernah berhenti',
      'Menjadi tempat pulang untuk banyak hati',
      'Keras pada diri sendiri, lembut pada yang dilindungi',
      'Kesabaran yang terlihat seperti keras kepala',
      'Selalu menepati janji yang tidak diucapkan',
    ],
    taglineCard: 'Bukan yang paling keras, tapi yang paling teguh.',
    kekuatanDescriptors: ['Pelindung Sunyi', 'Pijakan Setia', 'Visi Panjang'],
    bayanganDescriptors: ['Sulit Bergantung', 'Keras Kepala', 'Lambat Berubah'],
    dampakDescriptors: ['Tempat Bersandar saat Goyah', 'Pengingat untuk Tetap Berdiri'],
    sifatPills: [
      'mikir panjang, eksekusi tetap',
      'temennya sedikit tapi loyal',
      'tipe ngerencanain 5 tahun ke depan',
      'males drama, langsung ngomong',
    ],
  },
  '乙': {
    name: 'Tanaman Rambat',
    chinese: '乙木',
    subtitle: 'Sosok yang lentur dan tak mudah patah oleh keadaan.',
    tagline: 'Aku meliuk, tapi aku tidak pernah patah.',
    hero: 'Kamu melihat sebelum orang lain sadar apa yang harus dilihat. Di permukaan kamu lentur, mengikuti alur, tapi di dalam kamu sudah membaca seluruh peta sebelum melangkah. Kamu adalah pengamat paling tajam di ruangan itu, yang tertawa pelan, mengangguk, lalu tahu persis ke mana harus merambat selanjutnya.',
    identityPills: [
      'Mata yang menangkap segalanya',
      'Tidak pernah patah, cuma meliuk',
      'Strategi di balik sikap tenang',
      'Penjelajah celah kecil',
      'Lentur seperti air di batu',
      'Menunggu saat yang tepat',
      'Tumbuh di tempat sempit',
      'Tahu kapan harus menghilang',
      'Melihat potensi sebelum ada',
      'Kekuatan dalam adaptasi',
      'Tidak butuh jalan lurus',
      'Merambat diam-diam ke atas',
    ],
    traits: [
      'Mengubah rintangan jadi pijakan berikutnya',
      'Tidak mengumumkan rencana sebelum waktunya',
      'Pandai membaca emosi yang tidak diucapkan',
      'Bertahan dalam kondisi yang membuat orang lain menyerah',
      'Memilih jalur yang tidak terlihat orang lain',
      'Sabar yang terlihat seperti pasrah',
      'Selalu menemukan celah ketika semua pintu tertutup',
      'Tidak pernah lupa siapa yang membantu saat merambat',
    ],
    taglineCard: 'Meliuk, tapi tidak pernah patah.',
    kekuatanDescriptors: ['Pengamat Tajam', 'Adaptor Cepat', 'Strategi Halus'],
    bayanganDescriptors: ['Sulit Dibaca', 'Hindari Konfrontasi', 'Diam-diam Manipulatif'],
    dampakDescriptors: ['Ketenangan yang Menular', 'Solusi yang Tak Terduga'],
    sifatPills: [
      'banyak rencana, ga semua diumumin',
      'tahan banting tapi senyum terus',
      'tipe yang tau gosip duluan',
      'kalau ditolak, cari jalan lain',
    ],
  },
  '丙': {
    name: 'Matahari',
    chinese: '丙火',
    subtitle: 'Orang yang kehadirannya membuat sekitar terasa lebih hidup.',
    tagline: 'Aku hadir untuk menerangi, bukan untuk bersinar sendirian.',
    hero: 'Kamu yang bicara lebih dulu ketika semua orang masih ragu-ragu, lalu ruangan ikut bicara setelahnya. Energimu bukan sekadar semangat, itu adalah api yang membuat orang lain ingat kalau mereka juga hidup. Kamu tidak perlu menjadi pusat perhatian, kamu sudah menjadi alasan orang lain berani melangkah.',
    identityPills: [
      'Sinar pertama di pagi hari',
      'Menghangatkan tanpa syarat',
      'Tidak bisa diredupkan',
      'Penerang dalam kebingungan',
      'Api yang membakar keraguan',
      'Optimisme yang menular',
      'Hadir untuk memberi, bukan menuntut',
      'Matahari yang tidak kenal lelah',
      'Membuka jalan dengan cahaya',
      'Energi yang mengubah ruangan',
      'Menyala sebelum diminta',
      'Pemberi semangat paling jujur',
    ],
    traits: [
      'Melihat peluang di tempat orang lain melihat masalah',
      'Tidak bisa menyembunyikan perasaan, dan itu kekuatannya',
      'Memberi tanpa menghitung, tapi tidak lupa siapa yang menghargai',
      'Lelahnya tidak terlihat, karena dia tidak berhenti menyinari',
      'Sering dianggap kuat, jarang ditanya apakah butuh istirahat',
      'Tiba-tiba hilang, lalu muncul lagi lebih terang',
      'Membakar jembatan yang memang harus putus',
      'Hangatnya membuat orang lupa dia juga bisa membakar',
    ],
    taglineCard: 'Hadir untuk menerangi, bukan untuk bersinar sendirian.',
    kekuatanDescriptors: ['Pemimpin Alami', 'Tak Teredupkan', 'Optimisme Murni'],
    bayanganDescriptors: ['Butuh Panggung', 'Mudah Terbakar', 'Susah Diam'],
    dampakDescriptors: ['Penerang Ruangan', 'Kehangatan yang Dirasakan Orang Lain'],
    sifatPills: [
      'drama sebentar, move on cepet',
      'kalau cinta, totalitas',
      'kerja keras sampai lupa istirahat',
      'butuh pengakuan',
    ],
  },
  '丁': {
    name: 'Lilin',
    chinese: '丁火',
    subtitle: 'Pribadi yang menerangi sudut-sudut yang orang lain lewatkan.',
    tagline: 'Cahayaku kecil, tapi aku yang membuat kamu melihat dalam gelap.',
    hero: 'Cahayamu tidak menggelegar, tapi tepat di tengah gelap, kamulah yang masih setia menyala. Kamu tidak perlu menerangi seluruh dunia, cukup satu sudut yang kamu jaga dengan diam-diam. Kehadiranmu adalah alasan seseorang akhirnya bisa melihat apa yang selama ini kabur bagi mereka.',
    identityPills: [
      'Api yang tidak padam oleh angin',
      'Cahaya di jam-jam sepi',
      'Menuntun tanpa bicara',
      'Kehangatan yang konsisten',
      'Lilin di lorong gelap',
      'Menemani, bukan memimpin',
      'Setia pada nyalanya sendiri',
      'Menerangi yang terdekat dulu',
      'Fokus yang intens',
      'Cahaya kecil, dampak besar',
      'Tidak goyah oleh kegelapan',
      'Membakar diri untuk kebenaran',
    ],
    traits: [
      'Orang yang dicari ketika yang lain butuh kejelasan',
      'Kesetiaan yang diam, tapi tidak pernah padam',
      'Menerangi rahasia yang orang lain sembunyikan',
      'Tahu kapan harus meredup untuk bertahan',
      'Pendengar yang membuat orang berani jujur',
      'Kadang diabaikan, tapi cahayanya tidak luntur',
      'Mengorbankan diri diam-diam, lalu pura-pura tidak lelah',
      'Tidak perlu sorotan karena sudah menjadi arti bagi sekelilingnya',
    ],
    taglineCard: 'Cahaya kecil, tapi yang membuat kamu melihat dalam gelap.',
    kekuatanDescriptors: ['Insight Mendalam', 'Empati Akurat', 'Kreativitas Tenang'],
    bayanganDescriptors: ['Overthinking Akut', 'Sensitif Berlebihan', 'Burnout Diam-diam'],
    dampakDescriptors: ['Kehadiran yang Menenangkan', 'Pendengar yang Bikin Lega'],
    sifatPills: [
      'overthinker kelas dewa',
      'sayang sama yang gak sadar disayang',
      'curhat banyak tapi gak ngumbar',
      'romantis tapi gak dramatis',
    ],
  },
  '戊': {
    name: 'Gunung',
    chinese: '戊土',
    subtitle: 'Sosok yang menjadi tempat bersandar, tanpa banyak bicara.',
    tagline: 'Aku tidak bergerak, karena semua orang butuh tempat berpijak.',
    hero: 'Kamu adalah fondasi yang tidak terlihat di bawah gedung tertinggi. Semua orang mengagumi puncak, tapi hanya sedikit yang tahu bahwa di bawah sana, kamulah yang menahan semuanya. Kamu tidak bergerak oleh tren, oleh pujian, atau oleh ancaman, karena di dalam dirimu sudah ada peta yang tidak bisa diguncang.',
    identityPills: [
      'Pijakan yang tidak goyah',
      'Gunung yang menahan badai',
      'Fondasi di bawah gedung tinggi',
      'Tidak bergerak oleh angin',
      'Lambat berubah, tapi pasti',
      'Penjaga yang diam',
      'Ketinggian yang tidak perlu pengakuan',
      'Bumi yang menopang akar',
      'Stabilitas di tengah kacau',
      'Tidak mudah dipengaruhi',
      'Berat, tapi bisa diandalkan',
      'Menyangga diam-diam',
    ],
    traits: [
      'Orang yang ditelepon ketika semuanya runtuh',
      'Menyimpan beban banyak orang tanpa mengeluh',
      'Keputusan yang lama dibuat, tapi tidak pernah diubah',
      'Tidak mencari validasi, hanya butuh ruang untuk berdiri',
      'Kesetiaan yang membosankan, tapi tidak tergantikan',
      'Tidak akan mengikutimu ke tempat yang goyah',
      'Leganya orang lain saat tahu dia masih di sana',
      'Tidak bereaksi cepat, tapi reaksinya adalah yang paling tepat',
    ],
    taglineCard: 'Tidak bergerak, karena semua orang butuh tempat berpijak.',
    kekuatanDescriptors: ['Andalan Mutlak', 'Stabilitas Mental', 'Kesabaran Panjang'],
    bayanganDescriptors: ['Sulit Berubah', 'Emosi Tertutup', 'Lambat Memutuskan'],
    dampakDescriptors: ['Rasa Aman saat Kacau', 'Tempat Pulang yang Diam'],
    sifatPills: [
      'tipe yang ditelepon jam 3 pagi',
      'gak romantis tapi setia banget',
      'males drama, fokus yang penting',
      'ngomongnya dikit, kerjanya banyak',
    ],
  },
  '己': {
    name: 'Ladang',
    chinese: '己土',
    subtitle: 'Pribadi yang tumbuh pelan, tapi menguatkan banyak orang.',
    tagline: 'Aku bukan latar belakang. Aku adalah tanahnya.',
    hero: 'Kamu adalah tanah tempat segala sesuatu bermula. Bukan kamu yang dipetik, tapi dari dirimulah semuanya tumbuh. Kamu menerima benih yang orang lain buang, lalu diam-diam mengubahnya menjadi panen. Jarang diingat, tapi tanpa kamu, tidak ada yang bisa berdiri.',
    identityPills: [
      'Tanah yang subur',
      'Menumbuhkan yang diabaikan',
      'Menerima tanpa menghakimi',
      'Ladang tak bertepi',
      'Akar bagi sekeliling',
      'Kesuburan yang sunyi',
      'Melepaskan, lalu menuai',
      'Penyedia tanpa pamrih',
      'Tak mudah kosong, meski terus memberi',
      'Menyimpan benih masa depan',
      'Tempat kembali setelah lelah',
      'Bukan latar, tapi inti',
    ],
    traits: [
      'Memberi ruang untuk orang lain bertumbuh',
      'Sering diremehkan sampai hasilnya tampak',
      'Punya cadangan kekuatan yang tidak disadari',
      'Mencukupi banyak orang dari yang sederhana',
      'Memberi banyak, tanpa merasa berkurang',
      'Terlihat biasa, tapi isinya luar biasa',
      'Mengerti bahwa memberi adalah menanam, bukan membuang',
      'Setia dalam diam, tanpa perlu diakui',
    ],
    taglineCard: 'Bukan latar belakang. Tanahnya.',
    kekuatanDescriptors: ['Pengasuh Alami', 'Pemberi Tanpa Pamrih', 'Kesabaran Tanpa Batas'],
    bayanganDescriptors: ['Lupa Diri Sendiri', 'Susah Bilang Tidak', 'Pendendam Diam-diam'],
    dampakDescriptors: ['Tempat Tumbuh yang Aman', 'Orang yang Selalu Ada'],
    sifatPills: [
      'rela ngalah tapi ngitungin diam-diam',
      'masak banyak biar bisa bagi-bagi',
      'curhatan temen ngalir ke dia terus',
      'belanja buat keluarga dulu baru sendiri',
    ],
  },
  '庚': {
    name: 'Pedang',
    chinese: '庚金',
    subtitle: 'Pribadi yang memotong keraguan dengan keputusan tegas.',
    tagline: 'Aku memotong karena aku peduli pada yang benar.',
    hero: 'Kamu memotong bukan karena benci, tapi karena kamu tidak bisa melihat yang salah dan diam saja. Ada ketajaman dalam caramu melihat dunia, langsung, tanpa basa-basi, dan kadang membuat orang lain gentar. Tapi justru karena ketajaman itu, kamu tidak bisa dipakai untuk hal-hal yang tidak penting.',
    identityPills: [
      'Pedang bermata satu',
      'Memotong kebohongan',
      'Tajam dalam diam',
      'Tidak bisa dibengkokkan',
      'Prinsip di atas segalanya',
      'Tidak punya waktu untuk basa-basi',
      'Keadilan tanpa kompromi',
      'Bilah yang memisahkan benar dari nyaman',
      'Dingin, bukan kejam',
      'Menerobos ketidakjelasan',
      'Tidak untuk pajangan',
      'Berat, tapi pasti',
    ],
    traits: [
      'Orang yang mengatakan hal yang semua orang pikirkan tapi takut ucapkan',
      'Tidak bisa bersikap manis hanya untuk menjaga perasaan',
      'Pemotong lingkaran pertemanan yang tidak sehat',
      'Lebih memilih sendiri daripada bersama yang palsu',
      'Jujurnya membuat sakit, tapi menyembuhkan yang busuk',
      'Diamnya lebih menakutkan daripada marahnya',
      'Tidak ada abu-abu, hanya benar atau tidak benar',
      'Dihormati lebih dari disukai, dan itu cukup untuknya',
    ],
    taglineCard: 'Memotong karena peduli pada yang benar.',
    kekuatanDescriptors: ['Ketegasan Murni', 'Logika Tajam', 'Berani Konflik'],
    bayanganDescriptors: ['Kasar Tanpa Sadar', 'Tidak Sabaran', 'Sulit Memaafkan'],
    dampakDescriptors: ['Kejelasan yang Menyakitkan', 'Standar yang Memaksa Tumbuh'],
    sifatPills: [
      'kalau marah, langsung block',
      'gak suka basa-basi',
      'circle kecil tapi rapat',
      'mood swing tapi tetap logical',
    ],
  },
  '辛': {
    name: 'Permata',
    chinese: '辛金',
    subtitle: 'Sosok yang teliti, menghasilkan yang langka dan bernilai.',
    tagline: 'Bukan semua orang bisa melihat nilaimu. Itu bukan masalahmu.',
    hero: 'Kamu tidak berkilau untuk semua mata. Harganya hanya bisa dibaca oleh mereka yang sudah cukup lama mencari. Di dunia yang memuja yang mencolok, kamu adalah kemewahan yang tenang, tidak butuh pengakuan, tapi nilaimu tidak berkurang sedikit pun karena diabaikan.',
    identityPills: [
      'Cahaya yang tersembunyi',
      'Nilai yang tak lekang',
      'Permata di balik batu',
      'Tidak untuk semua orang',
      'Indah tanpa berusaha',
      'Ketajaman yang halus',
      'Kemewahan yang diam',
      'Ditemukan, bukan dipamerkan',
      'Kekerasan yang elegan',
      'Harga yang tidak ditawar',
      'Bukan kilau, tapi pancaran',
      'Menyimpan arti di dalam',
    ],
    traits: [
      'Tidak akan menjual murah, meski tidak ada yang menawar',
      'Menyembunyikan kedalaman di balik penampilan tenang',
      'Orang yang paling diremehkan sampai mereka butuh pertolongan',
      'Kecantikan yang tidak butuh validasi',
      'Kekuatan yang tidak kasar, tapi tidak bisa dihancurkan',
      'Bisa menyayat tanpa suara',
      'Memilih siapa yang boleh melihat isi sebenarnya',
      'Menunggu waktu yang tepat untuk berkilau, bukan karena tidak mampu',
    ],
    taglineCard: 'Tidak semua bisa melihat nilainya. Itu bukan masalahnya.',
    kekuatanDescriptors: ['Selera Tinggi', 'Presisi Estetika', 'Nilai Tak Tergantikan'],
    bayanganDescriptors: ['Standar Mustahil', 'Kritis Berlebihan', 'Eksklusif Diam-diam'],
    dampakDescriptors: ['Pengingat Kualitas', 'Validasi yang Sulit Didapat'],
    sifatPills: [
      'pemilih banget soal teman dan barang',
      'gak ngumumin pencapaian tapi keliatan',
      'kalau gak suka, dijauhin tanpa drama',
      'detail-oriented sampai bikin pusing sendiri',
    ],
  },
  '壬': {
    name: 'Samudra',
    chinese: '壬水',
    subtitle: 'Pribadi yang melihat jauh ke depan, melampaui yang tampak.',
    tagline: 'Aku tidak bisa dijelaskan. Aku hanya bisa dirasakan.',
    hero: 'Kamu tidak bisa dijelaskan, hanya bisa dirasakan. Seperti lautan yang luas, di permukaan kamu tenang, tapi di dalam menyimpan arus yang bisa membawa siapa saja ke tempat yang tidak terduga. Kamu adalah misteri yang tidak pernah selesai diungkap, dan itu bukan kelemahan, itu kekuatan.',
    identityPills: [
      'Samudra yang tidak bertepi',
      'Kedalaman yang tak terukur',
      'Arus di balik permukaan',
      'Tidak bisa dipetakan',
      'Misteri yang hidup',
      'Luas tanpa batas',
      'Membawa, tidak menahan',
      'Tenang, tapi mematikan',
      'Energi yang tidak terlihat',
      'Intuisi seluas cakrawala',
      'Tidak perlu dimengerti',
      'Mengalir tanpa henti',
    ],
    traits: [
      'Kadang kamu tidak mengerti dirimu sendiri, tapi orang lain percaya padamu',
      'Bisa menenangkan badai orang lain sambil menyimpan tsunami sendiri',
      'Berganti bentuk tanpa kehilangan volume',
      'Ditarik oleh bulan yang tidak dilihat orang lain',
      'Pendiam yang menyimpan seluruh semesta di dalam',
      'Tidak bisa dimiliki, tapi selalu dicari',
      'Menyembunyikan harta karun di kedalaman yang tidak sembarang orang selami',
      'Terlihat tidak terprediksi, padahal hanya mengikuti hukum alam yang lebih dalam',
    ],
    taglineCard: 'Tidak bisa dijelaskan. Hanya bisa dirasakan.',
    kekuatanDescriptors: ['Kedalaman Pikiran', 'Intuisi Tajam', 'Visi Tak Konvensional'],
    bayanganDescriptors: ['Mood Tak Terduga', 'Sulit Dipegang', 'Tenggelam Sendirian'],
    dampakDescriptors: ['Energi yang Sulit Dilupakan', 'Misteri yang Menarik'],
    sifatPills: [
      'mood-nya kayak cuaca tropis',
      'overthink banget pas malam',
      'kayaknya tau semua tapi diem aja',
      'tipe yang ngilang lalu muncul lagi',
    ],
  },
  '癸': {
    name: 'Hujan',
    chinese: '癸水',
    subtitle: 'Pribadi yang meresap dalam, memahami yang tak terucap.',
    tagline: 'Aku tidak selalu terlihat, tapi aku yang membuat segalanya tumbuh.',
    hero: 'Kamu datang tanpa suara, tapi setelah kepergianmu, semuanya tumbuh. Tidak semua orang menyadari kehadiranmu sampai mereka melihat tunas yang muncul di tanah yang kemarin masih kering. Kamu adalah kelembutan yang meresap paling dalam, menyentuh bagian yang tidak bisa dijangkau oleh kekuatan apa pun.',
    identityPills: [
      'Hujan di tanah kering',
      'Kelembutan yang meresap',
      'Datang diam-diam',
      'Menyuburkan yang layu',
      'Tidak pernah memaksa',
      'Menyentuh bagian terdalam',
      'Kesegaran yang dinanti',
      'Merembes, bukan menghantam',
      'Air yang menghidupkan',
      'Tidak terlihat tapi terasa',
      'Membawa kehidupan',
      'Tetes yang mengubah segalanya',
    ],
    traits: [
      'Menghilang setelah memberi, tanpa minta ucapan terima kasih',
      'Menyimpan air mata banyak orang tanpa memperlihatkan miliknya',
      'Kadang diremehkan sampai musim kemarau tiba',
      'Menyentuh hati yang paling keras dengan cara yang lembut',
      'Punya ritme sendiri yang tidak terburu-buru',
      'Menyediakan ruang tanpa mendikte apa yang harus tumbuh',
      'Tidak banyak bicara, tapi kehadirannya adalah jawaban',
      'Orang yang membuatmu merasa lebih baik tanpa kamu sadari',
    ],
    taglineCard: 'Tidak selalu terlihat, tapi yang membuat segalanya tumbuh.',
    kekuatanDescriptors: ['Empati Resapan', 'Sensitivitas Akurat', 'Kelembutan yang Kuat'],
    bayanganDescriptors: ['Menyerap Emosi Orang Lain', 'Batas Diri Tipis', 'Hilang Arah Sendiri'],
    dampakDescriptors: ['Bantuan yang Datang Diam-diam', 'Rasa Diterima Apa Adanya'],
    sifatPills: [
      'overthink plus overfeel, kombo lengkap',
      'tau lagi sedih tanpa ditanya',
      'nyaman jadi pendengar daripada bercerita',
      'butuh me-time biar gak meledak',
    ],
  },
}
